package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "photoshare")
public class Category implements java.io.Serializable {

	private Integer id;
	private String categoryName;
	private Date createdAt;
	private String description;
	private Date updatedAd;
	private Set<ImageCategory> imageCategories = new HashSet<ImageCategory>(0);

	public Category() {
	}

	public Category(String categoryName, Date createdAt, String description, Date updatedAd) {
		this.categoryName = categoryName;
		this.createdAt = createdAt;
		this.description = description;
		this.updatedAd = updatedAd;
	}

	public Category(String categoryName, Date createdAt, String description, Date updatedAd,
			Set<ImageCategory> imageCategories) {
		this.categoryName = categoryName;
		this.createdAt = createdAt;
		this.description = description;
		this.updatedAd = updatedAd;
		this.imageCategories = imageCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "category_name", nullable = false, length = 200)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "description", nullable = false, columnDefinition = "TEXT")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_ad", nullable = false, length = 10)
	public Date getUpdatedAd() {
		return this.updatedAd;
	}

	public void setUpdatedAd(Date updatedAd) {
		this.updatedAd = updatedAd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<ImageCategory> getImageCategories() {
		return this.imageCategories;
	}

	public void setImageCategories(Set<ImageCategory> imageCategories) {
		this.imageCategories = imageCategories;
	}

}
