package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "photoshare")
@Data
public class Category implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "category_name", nullable = false, length = 200)
    private String categoryName;

    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    private String description;

    @Temporal(TemporalType.DATE)
    @CreatedDate
    @Column(name = "created_at", nullable = false, length = 10)
    private Date createdAt = new Date();

    @Temporal(TemporalType.DATE)
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false, length = 10)
    private Date updatedAt = new Date();

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
    private Set<ImageCategory> imageCategories = new HashSet<ImageCategory>(0);

    public Category() {
    }

    public Category(String categoryName, String description) {
        this.categoryName = categoryName;
        this.description = description;
    }

    public Category(String categoryName, Date createdAt, String description, Date updatedAd,
                    Set<ImageCategory> imageCategories) {
        this.categoryName = categoryName;
        this.createdAt = createdAt;
        this.description = description;
        this.updatedAt = updatedAd;
        this.imageCategories = imageCategories;
    }

    public Category(Integer id, String categoryName, String description) {
        this.id = id;
        this.categoryName = categoryName;
        this.description = description;
    }
}
