package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.GenericGenerator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Collection generated by hbm2java
 */
@Entity
@Table(name = "collection", catalog = "photoshare")
public class Collection implements java.io.Serializable {

	private String id;
	private User user;
	private Date createdAt;
	private String description;
	private String name;
	private String status;
	private Date updatedAt;
	private Set<CollectionItem> collectionItems = new HashSet<CollectionItem>(0);

	public Collection() {
	}

	public Collection(String id, User user, Date createdAt, String description, String name, String status,
			Date updatedAt) {
		this.id = id;
		this.user = user;
		this.createdAt = createdAt;
		this.description = description;
		this.name = name;
		this.status = status;
		this.updatedAt = updatedAt;
	}

	public Collection(String id, User user, Date createdAt, String description, String name, String status,
			Date updatedAt, Set<CollectionItem> collectionItems) {
		this.id = id;
		this.user = user;
		this.createdAt = createdAt;
		this.description = description;
		this.name = name;
		this.status = status;
		this.updatedAt = updatedAt;
		this.collectionItems = collectionItems;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
	)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "description", nullable = false, columnDefinition = "TEXT")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false, length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collection")
	public Set<CollectionItem> getCollectionItems() {
		return this.collectionItems;
	}

	public void setCollectionItems(Set<CollectionItem> collectionItems) {
		this.collectionItems = collectionItems;
	}

}
