package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImageCategoryId generated by hbm2java
 */
@Embeddable
public class ImageCategoryId implements java.io.Serializable {

	private String imageId;
	private int categoryId;

	public ImageCategoryId() {
	}

	public ImageCategoryId(String imageId, int categoryId) {
		this.imageId = imageId;
		this.categoryId = categoryId;
	}

	@Column(name = "image_id", nullable = false)
	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImageCategoryId))
			return false;
		ImageCategoryId castOther = (ImageCategoryId) other;

		return ((this.getImageId() == castOther.getImageId()) || (this.getImageId() != null
				&& castOther.getImageId() != null && this.getImageId().equals(castOther.getImageId())))
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImageId() == null ? 0 : this.getImageId().hashCode());
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
