package com.eproject.backend.entities;
// Generated Feb 9, 2022, 12:16:02 AM by Hibernate Tools 5.1.10.Final

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImageCollectionId generated by hbm2java
 */
@Embeddable
@Data
public class ImageCollectionId implements java.io.Serializable {

    @Column(name = "image_id", nullable = false)
    private String imageId;

    @Column(name = "collection_id", nullable = false)
    private String collectionId;

    public ImageCollectionId() {
    }

    public ImageCollectionId(String imageId, String collectionId) {
        this.imageId = imageId;
        this.collectionId = collectionId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ImageCollectionId))
            return false;
        ImageCollectionId castOther = (ImageCollectionId) other;

        return ((this.getImageId() == castOther.getImageId()) || (this.getImageId() != null
                && castOther.getImageId() != null && this.getImageId().equals(castOther.getImageId())))
                && ((this.getCollectionId() == castOther.getCollectionId())
                || (this.getCollectionId() != null && castOther.getCollectionId() != null
                && this.getCollectionId().equals(castOther.getCollectionId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getImageId() == null ? 0 : this.getImageId().hashCode());
        result = 37 * result + (getCollectionId() == null ? 0 : this.getCollectionId().hashCode());
        return result;
    }

}
