package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImageCount generated by hbm2java
 */
@Entity
@Table(name = "image_count", catalog = "photoshare")
public class ImageCount implements java.io.Serializable {

	private String imageId;
	private int addCollectionCount;
	private int downloadCount;

	public ImageCount() {
	}

	public ImageCount(String imageId, int addCollectionCount, int downloadCount) {
		this.imageId = imageId;
		this.addCollectionCount = addCollectionCount;
		this.downloadCount = downloadCount;
	}

	@Id

	@Column(name = "image_id", unique = true, nullable = false)
	public String getImageId() {
		return this.imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	@Column(name = "add_collection_count", nullable = false)
	public int getAddCollectionCount() {
		return this.addCollectionCount;
	}

	public void setAddCollectionCount(int addCollectionCount) {
		this.addCollectionCount = addCollectionCount;
	}

	@Column(name = "download_count", nullable = false)
	public int getDownloadCount() {
		return this.downloadCount;
	}

	public void setDownloadCount(int downloadCount) {
		this.downloadCount = downloadCount;
	}

}
