package com.eproject.backend.entities;
// Generated Feb 9, 2022, 12:16:02 AM by Hibernate Tools 5.1.10.Final

import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageCollection generated by hbm2java
 */
@Entity
@Table(name = "image_collection", catalog = "photoshare")
@Getter
@Setter
@NoArgsConstructor
public class ImageCollection implements java.io.Serializable {

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "imageId", column = @Column(name = "image_id", nullable = false)),
            @AttributeOverride(name = "collectionId", column = @Column(name = "collection_id", nullable = false)) })
    private ImageCollectionId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "collection_id", nullable = false, insertable = false, updatable = false)
    private Collection collection;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "image_id", nullable = false, insertable = false, updatable = false)
    private Image image;

    public ImageCollection(ImageCollectionId id, Collection collection, Image image) {
        this.id = id;
        this.collection = collection;
        this.image = image;
    }

    public ImageCollection(Collection collection, Image image){
        this.collection = collection;
        this.image = image;
        this.id = new ImageCollectionId(image.getId(), collection.getId());
    }

}
