package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.GenericGenerator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "photoshare")
public class Image implements java.io.Serializable {

	private String id;
	private Date createdAt;
	private String imageInfo;
	private String imageUrl;
	private boolean isPremium;
	private Date updatedAt;
	private String userId;
	private Set<ImageCategory> imageCategories = new HashSet<ImageCategory>(0);

	public Image() {
	}

	public Image(String id, Date createdAt, String imageInfo, String imageUrl, boolean isPremium, Date updatedAt,
			String userId) {
		this.id = id;
		this.createdAt = createdAt;
		this.imageInfo = imageInfo;
		this.imageUrl = imageUrl;
		this.isPremium = isPremium;
		this.updatedAt = updatedAt;
		this.userId = userId;
	}

	public Image(String id, Date createdAt, String imageInfo, String imageUrl, boolean isPremium, Date updatedAt,
			String userId, Set<ImageCategory> imageCategories) {
		this.id = id;
		this.createdAt = createdAt;
		this.imageInfo = imageInfo;
		this.imageUrl = imageUrl;
		this.isPremium = isPremium;
		this.updatedAt = updatedAt;
		this.userId = userId;
		this.imageCategories = imageCategories;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
	)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "image_info", nullable = false)
	public String getImageInfo() {
		return this.imageInfo;
	}

	public void setImageInfo(String imageInfo) {
		this.imageInfo = imageInfo;
	}

	@Column(name = "image_url", nullable = false, length = 200)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "is_premium", nullable = false)
	public boolean isIsPremium() {
		return this.isPremium;
	}

	public void setIsPremium(boolean isPremium) {
		this.isPremium = isPremium;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 10)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "user_id", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	public Set<ImageCategory> getImageCategories() {
		return this.imageCategories;
	}

	public void setImageCategories(Set<ImageCategory> imageCategories) {
		this.imageCategories = imageCategories;
	}

}
