package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.GenericGenerator;

import java.util.Date;
import javax.persistence.*;

/**
 * MemberShip generated by hbm2java
 */
@Entity
@Table(name = "member_ship", catalog = "photoshare")
public class MemberShip implements java.io.Serializable {

	private String id;
	private Date createdAt;
	private String payment;
	private double pricing;
	private String userId;

	public MemberShip() {
	}

	public MemberShip(String id, Date createdAt, String payment, double pricing, String userId) {
		this.id = id;
		this.createdAt = createdAt;
		this.payment = payment;
		this.pricing = pricing;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
	)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "payment", nullable = false, length = 20)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Column(name = "pricing", nullable = false, precision = 22, scale = 0)
	public double getPricing() {
		return this.pricing;
	}

	public void setPricing(double pricing) {
		this.pricing = pricing;
	}

	@Column(name = "user_id", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
