package com.eproject.backend.entities;
// Generated Jan 3, 2022, 8:04:04 PM by Hibernate Tools 5.1.10.Final

import org.hibernate.annotations.GenericGenerator;

import java.util.Date;
import javax.persistence.*;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "token", catalog = "photoshare")
public class Token implements java.io.Serializable {

	private String id;
	private User user;
	private Date expireAt;
	private Date issuedAt;
	private Date notBefore;

	public Token() {
	}

	public Token(String id, User user, Date expireAt, Date issuedAt, Date notBefore) {
		this.id = id;
		this.user = user;
		this.expireAt = expireAt;
		this.issuedAt = issuedAt;
		this.notBefore = notBefore;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(generator = "UUID")
	@GenericGenerator(
			name = "UUID",
			strategy = "org.hibernate.id.UUIDGenerator"
	)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expire_at", nullable = false, length = 10)
	public Date getExpireAt() {
		return this.expireAt;
	}

	public void setExpireAt(Date expireAt) {
		this.expireAt = expireAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "issued_at", nullable = false, length = 10)
	public Date getIssuedAt() {
		return this.issuedAt;
	}

	public void setIssuedAt(Date issuedAt) {
		this.issuedAt = issuedAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "not_before", nullable = false, length = 10)
	public Date getNotBefore() {
		return this.notBefore;
	}

	public void setNotBefore(Date notBefore) {
		this.notBefore = notBefore;
	}

}
